### ISSUE TITLE
Support for inheritance?

### ISSUE THREAD

**Issue by richard-moss** [cs-cordero/py-ts-interfaces#10]
Hey - quick question: does the module support inheritance?

If I have
```
from dataclasses import dataclass
from py_ts_interfaces import Interface
from typing import get_type_hints as gth

@dataclass
class Simple(Interface):
    x: int
    y: str

@dataclass
class Simple2(Simple, Interface):
    z: str

print(gth(Simple2))
```
then I should have `Simple2` have elements x, y and z.  That's confirmed by get_type_hints, which returns
```
{'x': <class 'int'>, 'y': <class 'str'>, 'z': <class 'str'>}
```

But when I run py-ts on this I get an interface of:
```
interface Simple {
    x: number;
    y: string;
}

interface Simple2 {
    z: string;
}
```
...so Simple2 is missing the members x and y it should inherit from Simple.

**Comment by gjulianm** [comment]
Hello, this would be very useful to me too. @cs-cordero would you be open to reviewing a PR for this? I think it should not be very difficult to have a basic structure working

**Comment by cs-cordero** [comment]
Repo is going to archive read-only mode.
