### ISSUE TITLE
Add Support for Python 3.8+

### ISSUE THREAD

**Issue by kellyrmilligan** [cs-cordero/py-ts-interfaces#12]
it says those are supported, but i'm having trouble getting it to work. I am primarily a TS developer and not experienced with python just as FYI, I may be missing something silly. 

```
from dataclasses import dataclass
from py_ts_interfaces import Interface
from typings import Optional, Union

@dataclass
class Thing(Interface):
    show: bool
    value: float
    optional_field: Union[str, None] = None
```

```
from dataclasses import dataclass
from py_ts_interfaces import Interface
from typings import Optional, Union

@dataclass
class Thing(Interface):
    show: bool
    value: float
    optional_field: Optional[str] = None
```

first example gets me this:

```
AttributeError: 'ClassDef' object has no attribute 'value'
```

second attempt gets me this:

```
AttributeError: 'Name' object has no attribute 'value'
```

what am I missing?

**Comment by kellyrmilligan** [comment]
can't seem to define a `List` type either. 

```
@dataclass
class Brand(Interface):
    show: bool
    value: float
    brand_code: str


@dataclass
class BrandsResponse(Interface):
    data: List[Brand]
```

**Comment by kellyrmilligan** [comment]
only built in data types seem to work.

**Comment by cs-cordero** [comment]
Thanks for the bug report!

It definitely should be working, there is a unit test for `Union` here:  https://github.com/cs-cordero/py-ts-interfaces/blob/master/py_ts_interfaces/tests/tests.py#L263.  I just tested it in a Python 3.7.12 environment and it worked.

But I also tested it in a 3.9.13 environment and I got the same issue that you reported.  What version of Python are you running?  Let me know if you were also running a 3.7.x Python and still got the issue.

**Comment by cs-cordero** [comment]
Python versions tested:

- 3.7.12:  WORKS
- 3.8.13:  fails
- 3.9.13:  fails

**Comment by kellyrmilligan** [comment]
3.9.6

**Comment by kelly-tock** [comment]
More of a side question, but what is the intended way to use these generate interfaces? Generate a .d.ts file? Or should there be an option to export all the interfaces?

**Comment by kellyrmilligan** [comment]
answered my own question, sorry for the 2 users thing. I changed the output command to output a .d.ts file, and put it in a spot ts could find and was able to use the interfaces.

**Comment by cs-cordero** [comment]
This should be fixed now by the way.  Let me know if you still see issues, I've tested that this tool works now up through Python 3.10.5.
