### ISSUE TITLE
Support for datetime

### ISSUE THREAD

**Issue by rmargar** [cs-cordero/py-ts-interfaces#16]
Hey, would be great to add support for `datetime.datetime`.

Example:

```python
from dataclasses import dataclass
from datetime import datetime
from py_ts_interfaces import Interface

@dataclass 
class Foo(Interface):
     bar: datetime
```

would give us

```typescript
interface Foo{
     bar: Date;
}
```

**Comment by cs-cordero** [comment]
Hey there.  Thanks for opening this issue and for also the PR.  Deepest apologies for how long it took me to review this.

`datetime` is an [unsupported type](https://github.com/cs-cordero/py-ts-interfaces#unsupportedrejected-mappings) for this project.  While it may make sense at first glance to just transform `datetime` to `Date`, sending datetimes to-and-from the backend to the frontend and vice versa can be fraught with errors especially if timezones are involved.

I'd be happy with reopening this issue if there is enough demand for this feature in the opposite direction, but for now, I will close this ticket for now.
