### ISSUE TITLE
Help managing this repo?

### ISSUE THREAD

**Issue by adrienthiery** [cs-cordero/py-ts-interfaces#27]
Hi @cs-cordero , 

We started using your lib a while ago and have been happy using it, although we're seeing some good improvements we could provide there.

But we see some long-standing issues and not a lot of activity there.

Is there any specific reason for that?
Is there a better lib you started using? Is it just a question of free time for open-source?
Can we use in any way to manage this repo & provide and potentially merge some PRs?

Hopefully this reaches you alright, take care.
Adrien

**Comment by cs-cordero** [comment]
Repo is going to archive read-only mode.
