### ISSUE TITLE
AttributeError: 'TreeRebuilder' object has no attribute 'visit_typealias'

### ISSUE THREAD

**Issue by AdrKacz** [cs-cordero/py-ts-interfaces#28]
Hello,

Thank you very much for this very useful repo!

When running with **Python3.12.3** I get the following error: "**AttributeError: 'TreeRebuilder' object has no attribute 'visit_typealias'**" (using examples from the repo, so I assume the error was introduced by 3.12)

Do you know what this error mean and if there is a way to fix/debug it?

Thanks

**Comment by cs-cordero** [comment]
Repo is going to archive read-only mode.

Sorry I couldn't help out here.  You're more than welcome to fork the project if you're inclined.
