### ISSUE TITLE
[Feature Request] ts-py-interfaces wanted

### ISSUE THREAD

**Issue by huan** [cs-cordero/py-ts-interfaces#4]
Hi,

I'm a TypeScript fan and your project is fantastic.

Currently, I'm working on a project that translates a medium-size TypeScript project into Python.

There are lots of interfaces defined in the TypeScript. So it would be a huge help if your project can translate the basic TypeScript Interfaces into Python Data Class.

Do you have any plan to support the basic types from TS to PY, or do you know any project can do this job?

Thank you very much, and I hope you have a nice day!

Huan.

**Comment by cs-cordero** [comment]
Hi @huan !

Thanks for the kind words about the project, I hope that it is working well for you.

I understand the need to translate TypeScript into Python.  However, there are no plans to support auto-generation of types in the TS -> Python direction.

Why?  TypeScript's type system is incredibly matured, far _far_ beyond the capabilities of Python.  A lot of the Advanced type features (https://www.typescriptlang.org/docs/handbook/advanced-types.html#mapped-types) simply don't have a great way to be expressed in Python's type syntax.  It wasn't too long ago that in Python mypy finally got the `Literal` generic type!

I hope this explains it, even though my answer is sure to be disappointing.

I'll close this issue for now, but if there ends up being a path forward and a need among the community, we can reopen it.

**Comment by huan** [comment]
It's great to hear from you, thank you for replying me @cs-cordero !

I understand the TS is more complicated than the Python Typing, however, I believe if we could have a very basic translater, it might be a good start for the future works.

In my situation, even the simplest translator will be lots of help because I only need to translate many very basic `Interface` to Python `dataclass`, like the following:

```ts
export interface MyInterface {
  a: string
  b?: number
}
```

to

```python
@dataclass
class MyInterface:
  a: str
  b: Optional[int]
```

I would love to see any progress on this feature request, so please definitely let me know if there's any, and I'll try to study your code when I have time, to see if I can contribute some.
