### ISSUE TITLE
Support enums

### ISSUE THREAD

**Issue by cs-cordero** [cs-cordero/py-ts-interfaces#6]

**Comment by sakethsaxena** [comment]
Hey!
This is a very useful project and I would really love to have enums supported. 
Just wanted to know if you have any specific timeline in mind about adding support for enums?

**Comment by cs-cordero** [comment]
Hi there!   Thanks for checking out the project.  Unfortunately, I don't have a specific timeline in place for supporting enums.  Hopefully soon if I can find the time.  I'm more than happy to accept any pull requests from the community in case anyone wants to submit one.

**Comment by Plawn** [comment]
Hello, @sakethsaxena 

I don't know if you already found another solution for your problem but I'm currently developping petit-ts, which aims to provide typing export from python to typescript here:

https://github.com/Plawn/petit_ts

It provides Enum support and should be extensible in the future if required

**Comment by cs-cordero** [comment]
Repo is going to archive read-only mode.
